import type { Metadata } from "next";
import '@/shared/styles/globals.css';
import { ThemeProvider } from '@/app/_providers';
import { Navbar } from "@/entities/navbar/ui/navbar";
import { Footer } from "@/entities/footer/ui/footer";
import { mainContainer } from "./main.css";
import { SearchOverlay } from "@/features/search-post/ui/search-overlay";

// import './globals.css';

export const metadata: Metadata = {
  title: "JLOG",
  description: "JLOG Generated by create next app",
  icons: {
    icon : [
      "/favicon-32x32.png",
      "/favicon-16x16.png",
      "/favicon.ico"
    ],
    apple : [
      "/apple-touch-icon.png",
      "/android-chrome-512x512.png",
      "/android-chrome-192x192.png"
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <ThemeProvider>
          <Navbar />
            <SearchOverlay></SearchOverlay>
            <div className={mainContainer}>
              {children}
            </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
